### ISSUE TITLE
Overflow Breaking Page Layout

### ISSUE THREAD

**Issue by Kalebur** [WilJonze/wd2-toptracks#10]
There is overflow on the page and it's breaking the horizontal layout on larger screens. The issue seems to be related to the title header.

**Comment by WilJonze** [comment]
Hey James! Could you highlight the code that should be worked on?

**Comment by Kalebur** [comment]
Sure! The issue is coming from this block of CSS.

```
.header {
  background-color: var(--color-faded-white);
  padding: 0.5rem;
  margin: 0.5rem;
  color: var(--color-text);
  border-radius: var(--radius-header);
  text-align: center;
}
```
