### ISSUE TITLE
Create icons for upvotes and down votes.

### ISSUE THREAD

**Issue by qmonplaisir** [WilJonze/wd2-toptracks#11]
Should either look similar to this no fill just outlines
![like-and-unlike-button-isolated-icon-free-vector](https://user-images.githubusercontent.com/113145421/223539824-16aad46b-a7d8-4cd4-88c2-e3b03cfafe37.jpg)

or this
![390383-200](https://user-images.githubusercontent.com/113145421/223540702-fd530b2b-6eeb-4d38-8ddf-4c73616ee90b.png)

**Comment by WilJonze** [comment]
Icons have been created, and added in another issue.
