### ISSUE TITLE
Title Header

### ISSUE THREAD

**Issue by WilJonze** [WilJonze/wd2-toptracks#3]
To add a Title Header for the Landing Page. 

Pseudo Code:

```
<h1>TOP TRACKS</h1>
<h2>CK/CL's highest rated songs! </h2> 
```

- h2 element should have a 1 second fade in after page load. 
- Elements should be centered to the page
- Elements should be the same font as other text.
- h1 element should be clearly larger than the other text elements.

<img src="https://user-images.githubusercontent.com/103696024/222020894-a7f7ac71-89ca-4c24-a093-effe6270efb9.png" width=40%>

**Comment by Kalebur** [comment]
I'll get the title header set up.
