### ISSUE TITLE
Background

### ISSUE THREAD

**Issue by WilJonze** [WilJonze/wd2-toptracks#5]
Create a static linear gradient background with the following colors:

#7700a6
#fe00fe
#0016ee

Gradient should be vertical that spans the full length of the page. Meaning as you scroll the colors seen on screen will change. 
Reach out for further questions. 

STRETCH GOAL: Gradient will have a slight animation on scroll 

<img src="https://user-images.githubusercontent.com/103696024/222020894-a7f7ac71-89ca-4c24-a093-effe6270efb9.png" width=40%>

**Comment by Kalebur** [comment]
I'll get the background knocked out.
